---
- hosts: localhost
  become: yes
  vars:
    - user: 'jsorell'

  tasks:
    - name: "Install powerline packages"
      dnf: 
        name:
         - powerline
         - powerline-fonts
         - vim-powerline
        state: present

    - name: "set powerline in .bashrc file"
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        block: |
          if [ -f `which powerline-daemon` ]; then
            powerline-daemon -q
            POWERLINE_BASH_CONTINUATION=1
            POWERLINE_BASH_SELECT=1
            . /usr/share/powerline/bash/powerline.sh
          fi
    # Adding vim-powerline
    - name: "set vim-powerline in .vimrc file"
      blockinfile:
        path: "/home/{{ user }}/.vimrc"
        create: true
        marker: '" {mark} ANSIBLE MANAGED BLOCK '
        block: |
          python3 from powerline.vim import setup as powerline_setup
          python3 powerline_setup()
          python3 del powerline_setup
          set laststatus=2 " Always display the statusline in all windows
          set showtabline=2 " Always display the tabline, even if there is only one tab
          set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
          set t_Co=256